# /etc/mosdns/config.yaml
log:
  level: debug
  file: /var/log/mosdns.log
api:
  http: "0.0.0.0:9091"
include: []
plugins:
  - tag: whitelist
    type: domain_set
    args:
      files:
        - /etc/mosdns/rule/whitelist.txt
  - tag: hosts
    type: hosts
    args:
      files:
        - /etc/mosdns/rule/hosts.txt
  - tag: cloudflare_cidr
    type: ip_set
    args:
      files:
        - /etc/mosdns/rule/cloudflare-cidr.txt
  - tag: cfst_pool
    type: cfst_pool
    args:
      download_url: https://cfst.raenzo.com/test
      port: 443
      sample_count: 1000
      download_seconds: 5
      download_timeout: 5
      ping_times: 4
      routines: 200
      top_n: 5
      cache_file: /etc/mosdns/cfst_pool.json
      ipv6: false
      seed: 42
      fwmark: 0x42
  - tag: forward_mihomo
    type: forward
    args:
      upstreams:
        - addr: 127.0.0.1:2053
  - tag: forward_fallback
    type: forward
    args:
      upstreams:
        - addr: 223.5.5.5
  - tag: forward_upstream
    type: fallback
    args:
      primary: forward_mihomo
      secondary: forward_fallback
  - tag: main_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      # 白名单始终转发到上游
      - matches: "qname $whitelist"
        exec: $forward_upstream
      - matches: has_resp
        exec: accept
      # 根据hosts配置返回固定结果
      - exec: $hosts
      - matches: has_resp
        exec: accept
      # 转发到上游
      - exec: $forward_upstream
      # cloudflare优选
      - matches: resp_ip $cloudflare_cidr
        exec: lpush $cfst_pool
      - matches: has_resp
        exec: accept
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":1053"
  # 务必不要删tcp_server；DNS请求时，如果UDP数据包太大，会fallback到TCP
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":1053"
